### ISSUE TITLE
How to use this patch?

### ISSUE THREAD

**Issue by moneypi** [deathcoder/openai-flashgames-patch#1]
Would you please tell us how to use this patch?
I am not familar to the docker, and python.
Thanks very much.

**Comment by deathcoder** [comment]
Hi, the only thing you need to do is run the build.sh script.
this will create the patched docker image and will be automatically used by openai.

i copy here the answer i posted on the official issue that i reference in the readme and that goes more into the details of what happens:

after you run the build.sh you just run again your python agent and everything should work,
explanation in case you are interested:
when the python agent is ready to run the environment what it asks docker to load up a preconfigured 'vm' with the name quay.io/openai/universe.flashgames and version: 0.20.28
docker than proceeds to download the 'vm'( unless you already have it locally, this is key in why this works ) and starts it.
my script overrides your local image with a patched version, this means that whoever tries to use that image will be using the patched version without even knowing it
you may only run into problems if the image's version used by universe changes, in that case this trick will still work and is as easy as replacing the version '0.20.28' in both Dockerfile and the build.sh script with the new version
hope this helps

**Comment by moneypi** [comment]
Thanks very much, I can run DuskDrive now.
